### ISSUE TITLE
v0.1.2: "Add submodel element" button is broken 

### ISSUE THREAD

**Issue by s-heppner** [zrgt/pygui40aas#1]
Clicking the "Add submodel element" button 

![grafik](https://user-images.githubusercontent.com/94846071/154689726-a105d464-8c32-4196-86a0-1fbd1c2b85b2.png)

leads to the following error:

![grafik](https://user-images.githubusercontent.com/94846071/154689396-c00aa722-91c3-4ce3-b657-aaabf086fc58.png)

**Comment by zrgt** [comment]
Fixed in v.0.1.3
